issues:
  exclude-rules:
    # Exclude issues bypassing staticcheck.conf
    - linters:
        - staticcheck
      text: "SA1019:"
  max-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    # - gosimple
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused
    - vet

linters-settings:
  errcheck:
    exclude-functions: github.com/hashicorp/terraform-plugin-sdk/helper/schema:ForceNew|Set,fmt:.*,io:Close

run:
  skip-dirs:
    - vendor
  skip-files:
    - ".*_test.go"
  # change
  cache: true
  cache-ttl: 8760h

  modules-download-mode: vendor

  timeout: 60m
  # The default concurrency value is the number of available CPU.
  concurrency: 4
  # Allow multiple parallel golangci-lint instances running.
  # If false (default) - golangci-lint acquires file lock on start.
  allow-parallel-runners: true